/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.3.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *bubbleButton;
    QPushButton *insertionButton;
    QPushButton *quickButton;
    QPushButton *selectionButton;
    QPushButton *randomizeButton;
    QPushButton *exitButton;
    QFrame *menuLine1;
    QFrame *menuLine2;
    QLabel *menuLabel;
    QFrame *menuLine3;
    QFrame *displayLine1;
    QLabel *displayLabel;
    QFrame *num1;
    QFrame *num2;
    QFrame *num3;
    QFrame *num4;
    QFrame *num5;
    QFrame *num6;
    QFrame *num7;
    QFrame *num8;
    QFrame *num9;
    QFrame *num10;
    QFrame *num11;
    QFrame *num12;
    QFrame *num13;
    QFrame *num14;
    QFrame *num15;
    QFrame *num16;
    QFrame *num17;
    QFrame *num18;
    QFrame *num19;
    QFrame *num20;
    QFrame *num21;
    QFrame *num22;
    QFrame *num23;
    QFrame *num24;
    QFrame *num25;
    QFrame *num26;
    QFrame *num27;
    QFrame *num28;
    QFrame *num29;
    QFrame *num30;
    QFrame *num31;
    QFrame *num32;
    QFrame *num33;
    QFrame *num34;
    QFrame *num35;
    QFrame *num36;
    QFrame *num37;
    QFrame *num38;
    QFrame *num39;
    QFrame *num40;
    QFrame *num41;
    QFrame *num42;
    QFrame *num43;
    QFrame *num44;
    QFrame *num45;
    QFrame *num46;
    QFrame *num47;
    QFrame *num48;
    QFrame *num49;
    QFrame *num50;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(670, 421);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        bubbleButton = new QPushButton(centralwidget);
        bubbleButton->setObjectName(QString::fromUtf8("bubbleButton"));
        bubbleButton->setGeometry(QRect(570, 50, 91, 41));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(bubbleButton->sizePolicy().hasHeightForWidth());
        bubbleButton->setSizePolicy(sizePolicy);
        bubbleButton->setCursor(QCursor(Qt::PointingHandCursor));
        insertionButton = new QPushButton(centralwidget);
        insertionButton->setObjectName(QString::fromUtf8("insertionButton"));
        insertionButton->setGeometry(QRect(570, 170, 91, 41));
        sizePolicy.setHeightForWidth(insertionButton->sizePolicy().hasHeightForWidth());
        insertionButton->setSizePolicy(sizePolicy);
        insertionButton->setCursor(QCursor(Qt::PointingHandCursor));
        quickButton = new QPushButton(centralwidget);
        quickButton->setObjectName(QString::fromUtf8("quickButton"));
        quickButton->setGeometry(QRect(570, 230, 91, 41));
        sizePolicy.setHeightForWidth(quickButton->sizePolicy().hasHeightForWidth());
        quickButton->setSizePolicy(sizePolicy);
        quickButton->setCursor(QCursor(Qt::PointingHandCursor));
        selectionButton = new QPushButton(centralwidget);
        selectionButton->setObjectName(QString::fromUtf8("selectionButton"));
        selectionButton->setGeometry(QRect(570, 110, 91, 41));
        sizePolicy.setHeightForWidth(selectionButton->sizePolicy().hasHeightForWidth());
        selectionButton->setSizePolicy(sizePolicy);
        selectionButton->setCursor(QCursor(Qt::PointingHandCursor));
        randomizeButton = new QPushButton(centralwidget);
        randomizeButton->setObjectName(QString::fromUtf8("randomizeButton"));
        randomizeButton->setGeometry(QRect(570, 310, 91, 41));
        randomizeButton->setCursor(QCursor(Qt::PointingHandCursor));
        exitButton = new QPushButton(centralwidget);
        exitButton->setObjectName(QString::fromUtf8("exitButton"));
        exitButton->setGeometry(QRect(570, 370, 91, 41));
        exitButton->setCursor(QCursor(Qt::PointingHandCursor));
        menuLine1 = new QFrame(centralwidget);
        menuLine1->setObjectName(QString::fromUtf8("menuLine1"));
        menuLine1->setGeometry(QRect(540, 0, 41, 421));
        menuLine1->setFrameShape(QFrame::VLine);
        menuLine1->setFrameShadow(QFrame::Sunken);
        menuLine2 = new QFrame(centralwidget);
        menuLine2->setObjectName(QString::fromUtf8("menuLine2"));
        menuLine2->setGeometry(QRect(560, 280, 111, 20));
        menuLine2->setFrameShape(QFrame::HLine);
        menuLine2->setFrameShadow(QFrame::Sunken);
        menuLabel = new QLabel(centralwidget);
        menuLabel->setObjectName(QString::fromUtf8("menuLabel"));
        menuLabel->setGeometry(QRect(570, 0, 91, 31));
        QFont font;
        font.setPointSize(18);
        font.setBold(false);
        font.setUnderline(false);
        menuLabel->setFont(font);
        menuLabel->setLayoutDirection(Qt::LeftToRight);
        menuLabel->setAlignment(Qt::AlignCenter);
        menuLine3 = new QFrame(centralwidget);
        menuLine3->setObjectName(QString::fromUtf8("menuLine3"));
        menuLine3->setGeometry(QRect(560, 30, 118, 3));
        menuLine3->setFrameShape(QFrame::HLine);
        menuLine3->setFrameShadow(QFrame::Sunken);
        displayLine1 = new QFrame(centralwidget);
        displayLine1->setObjectName(QString::fromUtf8("displayLine1"));
        displayLine1->setGeometry(QRect(0, 350, 561, 20));
        displayLine1->setFrameShape(QFrame::HLine);
        displayLine1->setFrameShadow(QFrame::Sunken);
        displayLabel = new QLabel(centralwidget);
        displayLabel->setObjectName(QString::fromUtf8("displayLabel"));
        displayLabel->setGeometry(QRect(0, 359, 561, 61));
        QFont font1;
        font1.setPointSize(22);
        displayLabel->setFont(font1);
        displayLabel->setAlignment(Qt::AlignCenter);
        num1 = new QFrame(centralwidget);
        num1->setObjectName(QString::fromUtf8("num1"));
        num1->setGeometry(QRect(20, 330, 16, 30));
        QSizePolicy sizePolicy1(QSizePolicy::Maximum, QSizePolicy::Maximum);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(num1->sizePolicy().hasHeightForWidth());
        num1->setSizePolicy(sizePolicy1);
        num1->setFrameShadow(QFrame::Plain);
        num1->setLineWidth(3);
        num1->setMidLineWidth(3);
        num1->setFrameShape(QFrame::VLine);
        num2 = new QFrame(centralwidget);
        num2->setObjectName(QString::fromUtf8("num2"));
        num2->setGeometry(QRect(30, 110, 16, 250));
        sizePolicy1.setHeightForWidth(num2->sizePolicy().hasHeightForWidth());
        num2->setSizePolicy(sizePolicy1);
        num2->setFrameShadow(QFrame::Plain);
        num2->setLineWidth(3);
        num2->setMidLineWidth(3);
        num2->setFrameShape(QFrame::VLine);
        num3 = new QFrame(centralwidget);
        num3->setObjectName(QString::fromUtf8("num3"));
        num3->setGeometry(QRect(40, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num3->sizePolicy().hasHeightForWidth());
        num3->setSizePolicy(sizePolicy1);
        num3->setFrameShadow(QFrame::Plain);
        num3->setLineWidth(3);
        num3->setMidLineWidth(3);
        num3->setFrameShape(QFrame::VLine);
        num4 = new QFrame(centralwidget);
        num4->setObjectName(QString::fromUtf8("num4"));
        num4->setGeometry(QRect(50, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num4->sizePolicy().hasHeightForWidth());
        num4->setSizePolicy(sizePolicy1);
        num4->setFrameShadow(QFrame::Plain);
        num4->setLineWidth(3);
        num4->setMidLineWidth(3);
        num4->setFrameShape(QFrame::VLine);
        num5 = new QFrame(centralwidget);
        num5->setObjectName(QString::fromUtf8("num5"));
        num5->setGeometry(QRect(60, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num5->sizePolicy().hasHeightForWidth());
        num5->setSizePolicy(sizePolicy1);
        num5->setFrameShadow(QFrame::Plain);
        num5->setLineWidth(3);
        num5->setMidLineWidth(3);
        num5->setFrameShape(QFrame::VLine);
        num6 = new QFrame(centralwidget);
        num6->setObjectName(QString::fromUtf8("num6"));
        num6->setGeometry(QRect(70, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num6->sizePolicy().hasHeightForWidth());
        num6->setSizePolicy(sizePolicy1);
        num6->setFrameShadow(QFrame::Plain);
        num6->setLineWidth(3);
        num6->setMidLineWidth(3);
        num6->setFrameShape(QFrame::VLine);
        num7 = new QFrame(centralwidget);
        num7->setObjectName(QString::fromUtf8("num7"));
        num7->setGeometry(QRect(80, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num7->sizePolicy().hasHeightForWidth());
        num7->setSizePolicy(sizePolicy1);
        num7->setFrameShadow(QFrame::Plain);
        num7->setLineWidth(3);
        num7->setMidLineWidth(3);
        num7->setFrameShape(QFrame::VLine);
        num8 = new QFrame(centralwidget);
        num8->setObjectName(QString::fromUtf8("num8"));
        num8->setGeometry(QRect(90, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num8->sizePolicy().hasHeightForWidth());
        num8->setSizePolicy(sizePolicy1);
        num8->setFrameShadow(QFrame::Plain);
        num8->setLineWidth(3);
        num8->setMidLineWidth(3);
        num8->setFrameShape(QFrame::VLine);
        num9 = new QFrame(centralwidget);
        num9->setObjectName(QString::fromUtf8("num9"));
        num9->setGeometry(QRect(100, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num9->sizePolicy().hasHeightForWidth());
        num9->setSizePolicy(sizePolicy1);
        num9->setFrameShadow(QFrame::Plain);
        num9->setLineWidth(3);
        num9->setMidLineWidth(3);
        num9->setFrameShape(QFrame::VLine);
        num10 = new QFrame(centralwidget);
        num10->setObjectName(QString::fromUtf8("num10"));
        num10->setGeometry(QRect(110, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num10->sizePolicy().hasHeightForWidth());
        num10->setSizePolicy(sizePolicy1);
        num10->setFrameShadow(QFrame::Plain);
        num10->setLineWidth(3);
        num10->setMidLineWidth(3);
        num10->setFrameShape(QFrame::VLine);
        num11 = new QFrame(centralwidget);
        num11->setObjectName(QString::fromUtf8("num11"));
        num11->setGeometry(QRect(120, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num11->sizePolicy().hasHeightForWidth());
        num11->setSizePolicy(sizePolicy1);
        num11->setFrameShadow(QFrame::Plain);
        num11->setLineWidth(3);
        num11->setMidLineWidth(3);
        num11->setFrameShape(QFrame::VLine);
        num12 = new QFrame(centralwidget);
        num12->setObjectName(QString::fromUtf8("num12"));
        num12->setGeometry(QRect(130, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num12->sizePolicy().hasHeightForWidth());
        num12->setSizePolicy(sizePolicy1);
        num12->setFrameShadow(QFrame::Plain);
        num12->setLineWidth(3);
        num12->setMidLineWidth(3);
        num12->setFrameShape(QFrame::VLine);
        num13 = new QFrame(centralwidget);
        num13->setObjectName(QString::fromUtf8("num13"));
        num13->setGeometry(QRect(140, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num13->sizePolicy().hasHeightForWidth());
        num13->setSizePolicy(sizePolicy1);
        num13->setFrameShadow(QFrame::Plain);
        num13->setLineWidth(3);
        num13->setMidLineWidth(3);
        num13->setFrameShape(QFrame::VLine);
        num14 = new QFrame(centralwidget);
        num14->setObjectName(QString::fromUtf8("num14"));
        num14->setGeometry(QRect(150, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num14->sizePolicy().hasHeightForWidth());
        num14->setSizePolicy(sizePolicy1);
        num14->setFrameShadow(QFrame::Plain);
        num14->setLineWidth(3);
        num14->setMidLineWidth(3);
        num14->setFrameShape(QFrame::VLine);
        num15 = new QFrame(centralwidget);
        num15->setObjectName(QString::fromUtf8("num15"));
        num15->setGeometry(QRect(160, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num15->sizePolicy().hasHeightForWidth());
        num15->setSizePolicy(sizePolicy1);
        num15->setFrameShadow(QFrame::Plain);
        num15->setLineWidth(3);
        num15->setMidLineWidth(3);
        num15->setFrameShape(QFrame::VLine);
        num16 = new QFrame(centralwidget);
        num16->setObjectName(QString::fromUtf8("num16"));
        num16->setGeometry(QRect(170, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num16->sizePolicy().hasHeightForWidth());
        num16->setSizePolicy(sizePolicy1);
        num16->setFrameShadow(QFrame::Plain);
        num16->setLineWidth(3);
        num16->setMidLineWidth(3);
        num16->setFrameShape(QFrame::VLine);
        num17 = new QFrame(centralwidget);
        num17->setObjectName(QString::fromUtf8("num17"));
        num17->setGeometry(QRect(180, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num17->sizePolicy().hasHeightForWidth());
        num17->setSizePolicy(sizePolicy1);
        num17->setFrameShadow(QFrame::Plain);
        num17->setLineWidth(3);
        num17->setMidLineWidth(3);
        num17->setFrameShape(QFrame::VLine);
        num18 = new QFrame(centralwidget);
        num18->setObjectName(QString::fromUtf8("num18"));
        num18->setGeometry(QRect(190, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num18->sizePolicy().hasHeightForWidth());
        num18->setSizePolicy(sizePolicy1);
        num18->setFrameShadow(QFrame::Plain);
        num18->setLineWidth(3);
        num18->setMidLineWidth(3);
        num18->setFrameShape(QFrame::VLine);
        num19 = new QFrame(centralwidget);
        num19->setObjectName(QString::fromUtf8("num19"));
        num19->setGeometry(QRect(200, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num19->sizePolicy().hasHeightForWidth());
        num19->setSizePolicy(sizePolicy1);
        num19->setFrameShadow(QFrame::Plain);
        num19->setLineWidth(3);
        num19->setMidLineWidth(3);
        num19->setFrameShape(QFrame::VLine);
        num20 = new QFrame(centralwidget);
        num20->setObjectName(QString::fromUtf8("num20"));
        num20->setGeometry(QRect(210, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num20->sizePolicy().hasHeightForWidth());
        num20->setSizePolicy(sizePolicy1);
        num20->setFrameShadow(QFrame::Plain);
        num20->setLineWidth(3);
        num20->setMidLineWidth(3);
        num20->setFrameShape(QFrame::VLine);
        num21 = new QFrame(centralwidget);
        num21->setObjectName(QString::fromUtf8("num21"));
        num21->setGeometry(QRect(220, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num21->sizePolicy().hasHeightForWidth());
        num21->setSizePolicy(sizePolicy1);
        num21->setFrameShadow(QFrame::Plain);
        num21->setLineWidth(3);
        num21->setMidLineWidth(3);
        num21->setFrameShape(QFrame::VLine);
        num22 = new QFrame(centralwidget);
        num22->setObjectName(QString::fromUtf8("num22"));
        num22->setGeometry(QRect(230, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num22->sizePolicy().hasHeightForWidth());
        num22->setSizePolicy(sizePolicy1);
        num22->setFrameShadow(QFrame::Plain);
        num22->setLineWidth(3);
        num22->setMidLineWidth(3);
        num22->setFrameShape(QFrame::VLine);
        num23 = new QFrame(centralwidget);
        num23->setObjectName(QString::fromUtf8("num23"));
        num23->setGeometry(QRect(240, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num23->sizePolicy().hasHeightForWidth());
        num23->setSizePolicy(sizePolicy1);
        num23->setFrameShadow(QFrame::Plain);
        num23->setLineWidth(3);
        num23->setMidLineWidth(3);
        num23->setFrameShape(QFrame::VLine);
        num24 = new QFrame(centralwidget);
        num24->setObjectName(QString::fromUtf8("num24"));
        num24->setGeometry(QRect(250, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num24->sizePolicy().hasHeightForWidth());
        num24->setSizePolicy(sizePolicy1);
        num24->setFrameShadow(QFrame::Plain);
        num24->setLineWidth(3);
        num24->setMidLineWidth(3);
        num24->setFrameShape(QFrame::VLine);
        num25 = new QFrame(centralwidget);
        num25->setObjectName(QString::fromUtf8("num25"));
        num25->setGeometry(QRect(260, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num25->sizePolicy().hasHeightForWidth());
        num25->setSizePolicy(sizePolicy1);
        num25->setFrameShadow(QFrame::Plain);
        num25->setLineWidth(3);
        num25->setMidLineWidth(3);
        num25->setFrameShape(QFrame::VLine);
        num26 = new QFrame(centralwidget);
        num26->setObjectName(QString::fromUtf8("num26"));
        num26->setGeometry(QRect(270, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num26->sizePolicy().hasHeightForWidth());
        num26->setSizePolicy(sizePolicy1);
        num26->setFrameShadow(QFrame::Plain);
        num26->setLineWidth(3);
        num26->setMidLineWidth(3);
        num26->setFrameShape(QFrame::VLine);
        num27 = new QFrame(centralwidget);
        num27->setObjectName(QString::fromUtf8("num27"));
        num27->setGeometry(QRect(280, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num27->sizePolicy().hasHeightForWidth());
        num27->setSizePolicy(sizePolicy1);
        num27->setFrameShadow(QFrame::Plain);
        num27->setLineWidth(3);
        num27->setMidLineWidth(3);
        num27->setFrameShape(QFrame::VLine);
        num28 = new QFrame(centralwidget);
        num28->setObjectName(QString::fromUtf8("num28"));
        num28->setGeometry(QRect(290, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num28->sizePolicy().hasHeightForWidth());
        num28->setSizePolicy(sizePolicy1);
        num28->setFrameShadow(QFrame::Plain);
        num28->setLineWidth(3);
        num28->setMidLineWidth(3);
        num28->setFrameShape(QFrame::VLine);
        num29 = new QFrame(centralwidget);
        num29->setObjectName(QString::fromUtf8("num29"));
        num29->setGeometry(QRect(300, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num29->sizePolicy().hasHeightForWidth());
        num29->setSizePolicy(sizePolicy1);
        num29->setFrameShadow(QFrame::Plain);
        num29->setLineWidth(3);
        num29->setMidLineWidth(3);
        num29->setFrameShape(QFrame::VLine);
        num30 = new QFrame(centralwidget);
        num30->setObjectName(QString::fromUtf8("num30"));
        num30->setGeometry(QRect(310, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num30->sizePolicy().hasHeightForWidth());
        num30->setSizePolicy(sizePolicy1);
        num30->setFrameShadow(QFrame::Plain);
        num30->setLineWidth(3);
        num30->setMidLineWidth(3);
        num30->setFrameShape(QFrame::VLine);
        num31 = new QFrame(centralwidget);
        num31->setObjectName(QString::fromUtf8("num31"));
        num31->setGeometry(QRect(320, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num31->sizePolicy().hasHeightForWidth());
        num31->setSizePolicy(sizePolicy1);
        num31->setFrameShadow(QFrame::Plain);
        num31->setLineWidth(3);
        num31->setMidLineWidth(3);
        num31->setFrameShape(QFrame::VLine);
        num32 = new QFrame(centralwidget);
        num32->setObjectName(QString::fromUtf8("num32"));
        num32->setGeometry(QRect(330, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num32->sizePolicy().hasHeightForWidth());
        num32->setSizePolicy(sizePolicy1);
        num32->setFrameShadow(QFrame::Plain);
        num32->setLineWidth(3);
        num32->setMidLineWidth(3);
        num32->setFrameShape(QFrame::VLine);
        num33 = new QFrame(centralwidget);
        num33->setObjectName(QString::fromUtf8("num33"));
        num33->setGeometry(QRect(340, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num33->sizePolicy().hasHeightForWidth());
        num33->setSizePolicy(sizePolicy1);
        num33->setFrameShadow(QFrame::Plain);
        num33->setLineWidth(3);
        num33->setMidLineWidth(3);
        num33->setFrameShape(QFrame::VLine);
        num34 = new QFrame(centralwidget);
        num34->setObjectName(QString::fromUtf8("num34"));
        num34->setGeometry(QRect(350, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num34->sizePolicy().hasHeightForWidth());
        num34->setSizePolicy(sizePolicy1);
        num34->setFrameShadow(QFrame::Plain);
        num34->setLineWidth(3);
        num34->setMidLineWidth(3);
        num34->setFrameShape(QFrame::VLine);
        num35 = new QFrame(centralwidget);
        num35->setObjectName(QString::fromUtf8("num35"));
        num35->setGeometry(QRect(360, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num35->sizePolicy().hasHeightForWidth());
        num35->setSizePolicy(sizePolicy1);
        num35->setFrameShadow(QFrame::Plain);
        num35->setLineWidth(3);
        num35->setMidLineWidth(3);
        num35->setFrameShape(QFrame::VLine);
        num36 = new QFrame(centralwidget);
        num36->setObjectName(QString::fromUtf8("num36"));
        num36->setGeometry(QRect(370, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num36->sizePolicy().hasHeightForWidth());
        num36->setSizePolicy(sizePolicy1);
        num36->setFrameShadow(QFrame::Plain);
        num36->setLineWidth(3);
        num36->setMidLineWidth(3);
        num36->setFrameShape(QFrame::VLine);
        num37 = new QFrame(centralwidget);
        num37->setObjectName(QString::fromUtf8("num37"));
        num37->setGeometry(QRect(380, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num37->sizePolicy().hasHeightForWidth());
        num37->setSizePolicy(sizePolicy1);
        num37->setFrameShadow(QFrame::Plain);
        num37->setLineWidth(3);
        num37->setMidLineWidth(3);
        num37->setFrameShape(QFrame::VLine);
        num38 = new QFrame(centralwidget);
        num38->setObjectName(QString::fromUtf8("num38"));
        num38->setGeometry(QRect(390, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num38->sizePolicy().hasHeightForWidth());
        num38->setSizePolicy(sizePolicy1);
        num38->setFrameShadow(QFrame::Plain);
        num38->setLineWidth(3);
        num38->setMidLineWidth(3);
        num38->setFrameShape(QFrame::VLine);
        num39 = new QFrame(centralwidget);
        num39->setObjectName(QString::fromUtf8("num39"));
        num39->setGeometry(QRect(400, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num39->sizePolicy().hasHeightForWidth());
        num39->setSizePolicy(sizePolicy1);
        num39->setFrameShadow(QFrame::Plain);
        num39->setLineWidth(3);
        num39->setMidLineWidth(3);
        num39->setFrameShape(QFrame::VLine);
        num40 = new QFrame(centralwidget);
        num40->setObjectName(QString::fromUtf8("num40"));
        num40->setGeometry(QRect(410, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num40->sizePolicy().hasHeightForWidth());
        num40->setSizePolicy(sizePolicy1);
        num40->setFrameShadow(QFrame::Plain);
        num40->setLineWidth(3);
        num40->setMidLineWidth(3);
        num40->setFrameShape(QFrame::VLine);
        num41 = new QFrame(centralwidget);
        num41->setObjectName(QString::fromUtf8("num41"));
        num41->setGeometry(QRect(420, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num41->sizePolicy().hasHeightForWidth());
        num41->setSizePolicy(sizePolicy1);
        num41->setFrameShadow(QFrame::Plain);
        num41->setLineWidth(3);
        num41->setMidLineWidth(3);
        num41->setFrameShape(QFrame::VLine);
        num42 = new QFrame(centralwidget);
        num42->setObjectName(QString::fromUtf8("num42"));
        num42->setGeometry(QRect(430, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num42->sizePolicy().hasHeightForWidth());
        num42->setSizePolicy(sizePolicy1);
        num42->setFrameShadow(QFrame::Plain);
        num42->setLineWidth(3);
        num42->setMidLineWidth(3);
        num42->setFrameShape(QFrame::VLine);
        num43 = new QFrame(centralwidget);
        num43->setObjectName(QString::fromUtf8("num43"));
        num43->setGeometry(QRect(440, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num43->sizePolicy().hasHeightForWidth());
        num43->setSizePolicy(sizePolicy1);
        num43->setFrameShadow(QFrame::Plain);
        num43->setLineWidth(3);
        num43->setMidLineWidth(3);
        num43->setFrameShape(QFrame::VLine);
        num44 = new QFrame(centralwidget);
        num44->setObjectName(QString::fromUtf8("num44"));
        num44->setGeometry(QRect(450, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num44->sizePolicy().hasHeightForWidth());
        num44->setSizePolicy(sizePolicy1);
        num44->setFrameShadow(QFrame::Plain);
        num44->setLineWidth(3);
        num44->setMidLineWidth(3);
        num44->setFrameShape(QFrame::VLine);
        num45 = new QFrame(centralwidget);
        num45->setObjectName(QString::fromUtf8("num45"));
        num45->setGeometry(QRect(460, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num45->sizePolicy().hasHeightForWidth());
        num45->setSizePolicy(sizePolicy1);
        num45->setFrameShadow(QFrame::Plain);
        num45->setLineWidth(3);
        num45->setMidLineWidth(3);
        num45->setFrameShape(QFrame::VLine);
        num46 = new QFrame(centralwidget);
        num46->setObjectName(QString::fromUtf8("num46"));
        num46->setGeometry(QRect(470, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num46->sizePolicy().hasHeightForWidth());
        num46->setSizePolicy(sizePolicy1);
        num46->setFrameShadow(QFrame::Plain);
        num46->setLineWidth(3);
        num46->setMidLineWidth(3);
        num46->setFrameShape(QFrame::VLine);
        num47 = new QFrame(centralwidget);
        num47->setObjectName(QString::fromUtf8("num47"));
        num47->setGeometry(QRect(480, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num47->sizePolicy().hasHeightForWidth());
        num47->setSizePolicy(sizePolicy1);
        num47->setFrameShadow(QFrame::Plain);
        num47->setLineWidth(3);
        num47->setMidLineWidth(3);
        num47->setFrameShape(QFrame::VLine);
        num48 = new QFrame(centralwidget);
        num48->setObjectName(QString::fromUtf8("num48"));
        num48->setGeometry(QRect(490, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num48->sizePolicy().hasHeightForWidth());
        num48->setSizePolicy(sizePolicy1);
        num48->setFrameShadow(QFrame::Plain);
        num48->setLineWidth(3);
        num48->setMidLineWidth(3);
        num48->setFrameShape(QFrame::VLine);
        num49 = new QFrame(centralwidget);
        num49->setObjectName(QString::fromUtf8("num49"));
        num49->setGeometry(QRect(500, 60, 16, 301));
        sizePolicy1.setHeightForWidth(num49->sizePolicy().hasHeightForWidth());
        num49->setSizePolicy(sizePolicy1);
        num49->setFrameShadow(QFrame::Plain);
        num49->setLineWidth(3);
        num49->setMidLineWidth(3);
        num49->setFrameShape(QFrame::VLine);
        num50 = new QFrame(centralwidget);
        num50->setObjectName(QString::fromUtf8("num50"));
        num50->setGeometry(QRect(510, 30, 16, 330));
        sizePolicy1.setHeightForWidth(num50->sizePolicy().hasHeightForWidth());
        num50->setSizePolicy(sizePolicy1);
        num50->setFrameShadow(QFrame::Plain);
        num50->setLineWidth(3);
        num50->setMidLineWidth(3);
        num50->setFrameShape(QFrame::VLine);
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);
        QObject::connect(exitButton, &QPushButton::clicked, MainWindow, qOverload<>(&QMainWindow::close));

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        bubbleButton->setText(QCoreApplication::translate("MainWindow", "Bubble Sort", nullptr));
        insertionButton->setText(QCoreApplication::translate("MainWindow", "Insertion Sort", nullptr));
        quickButton->setText(QCoreApplication::translate("MainWindow", "Quick Sort", nullptr));
        selectionButton->setText(QCoreApplication::translate("MainWindow", "Selection Sort", nullptr));
        randomizeButton->setText(QCoreApplication::translate("MainWindow", "Randomize", nullptr));
        exitButton->setText(QCoreApplication::translate("MainWindow", "Exit", nullptr));
        menuLabel->setText(QCoreApplication::translate("MainWindow", "Menu", nullptr));
        displayLabel->setText(QCoreApplication::translate("MainWindow", "Press any sort to begin...", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
